# Generated by Django 4.1 on 2022-08-30 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_suggestion_alter_schedule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='is_confirmed',
            field=models.BooleanField(default=True, verbose_name='確定したか'),
        ),
    ]
